/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KKrb6kngms4
 */
import { Button } from "@/components/ui/button"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"

export function MainUI() {
  return (
    <div className="min-h-screen w-full">
      <header className="flex h-14 lg:h-[60px] items-center gap-4 border-b bg-gray-100/40 px-6 dark:bg-gray-800/40">
        <div className="w-full flex-1" />
        <div className="flex items-center gap-2">
          <Button>Connect Wallet</Button>
          <div className="px-2 py-1 bg-green-500 text-white rounded-md text-sm">Free transactions</div>
        </div>
      </header>
      <div className="grid w-full lg:grid-cols-[280px_1fr_280px]">
        <div className="hidden border-r bg-gray-100/40 lg:block dark:bg-gray-800/40">
          <Card className="m-4">
            <CardHeader className="pb-4">
              <CardTitle>Mint New NFT</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-1">
                <Label htmlFor="nftName">Name</Label>
                <Input id="nftName" />
              </div>
              <div className="space-y-1">
                <Label htmlFor="nftImage">Image URL</Label>
                <Input id="nftImage" />
              </div>
              <Button className="mt-4">Mint NFT</Button>
            </CardContent>
          </Card>
        </div>
        <div className="flex flex-col">
          <main className="grid grid-cols-3 gap-4 p-4 md:gap-8 md:p-6">
            <Card>
              <CardHeader className="pb-4">
                <CardTitle className="text-center">NFT 1</CardTitle>
              </CardHeader>
              <CardContent>
                <img
                  alt="NFT 1"
                  className="mx-auto"
                  height="150"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "150/150",
                    objectFit: "cover",
                  }}
                  width="150"
                />
              </CardContent>
            </Card>
          </main>
        </div>
        <div className="hidden border-l bg-gray-100/40 lg:block dark:bg-gray-800/40">
          <Card className="m-4">
            <CardHeader className="pb-4">
              <CardTitle>NFT Details</CardTitle>
            </CardHeader>
            <CardContent>
              <img
                alt="NFT Details"
                className="mx-auto my-4"
                height="300"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/300",
                  objectFit: "cover",
                }}
                width="300"
              />
              <div className="space-y-1">
                <Label>Name</Label>
                <p className="text-gray-500">NFT 1</p>
                <Label>Owner</Label>
                <p className="text-gray-500">0x1234...5678</p>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
