/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.71.0
  Forc version: 0.48.1
  Fuel-Core version: 0.22.0
*/

import type {
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

import type { Enum } from "./common";

export enum ErrorsInput { InvalidSignature = 'InvalidSignature' };
export enum ErrorsOutput { InvalidSignature = 'InvalidSignature' };

export type AddressInput = { value: string };
export type AddressOutput = AddressInput;

interface PacketMinterAbiInterface extends Interface {
  functions: {
    mint_packet: FunctionFragment;
    set_packet_predicate: FunctionFragment;
    set_signer: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'mint_packet', values: [AddressInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'set_packet_predicate', values: [AddressInput]): Uint8Array;
  encodeFunctionData(functionFragment: 'set_signer', values: [AddressInput]): Uint8Array;

  decodeFunctionData(functionFragment: 'mint_packet', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'set_packet_predicate', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'set_signer', data: BytesLike): DecodedValue;
}

export class PacketMinterAbi extends Contract {
  interface: PacketMinterAbiInterface;
  functions: {
    mint_packet: InvokeFunction<[subject: AddressInput], void>;
    set_packet_predicate: InvokeFunction<[packet_addr: AddressInput], void>;
    set_signer: InvokeFunction<[signer: AddressInput], void>;
  };
}
