/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.71.0
  Forc version: 0.48.1
  Fuel-Core version: 0.22.0
*/

import type {
  BigNumberish,
  BN,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

import type { Option } from "./common";

export type AddressInput = { value: string };
export type AddressOutput = AddressInput;

export type PacketPredicateAbiConfigurables = {
  SIGNER: AddressInput;
};

interface PacketPredicateAbiInterface extends Interface {
  functions: {
    main: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'main', values: [Option<BigNumberish>]): Uint8Array;

  decodeFunctionData(functionFragment: 'main', data: BytesLike): DecodedValue;
}

export class PacketPredicateAbi extends Contract {
  interface: PacketPredicateAbiInterface;
  functions: {
    main: InvokeFunction<[signature_witness_id: Option<BigNumberish>], boolean>;
  };
}
